### ISSUE TITLE
[Titanfall 2] Incorrect and missing MilesLanguageIDs

### ISSUE THREAD

**Issue by Gazyi** [r-ex/LegionPlus#108]
Some language indexes are missing: Latin America Spanish and Portuguese. And all indexes after Polish language are incorrect. 

I have region locked copy from Origin, which has only Polish and Russian localizations. Legion+ doesn't load russian language banks, because those banks return Mandarin ID according to program. I've modified code a bit to log what LocalizeIndex banks return.

```[19:47:48] [I] Load rpak: I:\Games\Titanfall2\r2\sound\general.mbnk
[19:47:49] [I] LocalizeIndex: Polish
[19:47:49] [I] SelectedLanguage: Russian
[19:47:49] [I] LocalizeIndex: Polish
[19:47:49] [I] SelectedLanguage: Russian
[19:47:49] [I] LocalizeIndex: Polish
[19:47:49] [I] SelectedLanguage: Russian
[19:47:49] [I] LocalizeIndex: Polish
[19:47:49] [I] SelectedLanguage: Russian
[19:47:49] [I] LocalizeIndex: Polish
[19:47:49] [I] SelectedLanguage: Russian
[19:47:49] [I] LocalizeIndex: Polish
[19:47:49] [I] SelectedLanguage: Russian
[19:47:49] [I] LocalizeIndex: Polish
[19:47:49] [I] SelectedLanguage: Russian
[19:47:49] [I] LocalizeIndex: Polish
[19:47:49] [I] SelectedLanguage: Russian
[19:47:49] [I] LocalizeIndex: Polish
[19:47:49] [I] SelectedLanguage: Russian
[19:47:49] [I] LocalizeIndex: Mandarin
[19:47:49] [I] SelectedLanguage: Russian
[19:47:49] [I] LocalizeIndex: Mandarin
[19:47:49] [I] SelectedLanguage: Russian
[19:47:49] [I] LocalizeIndex: Mandarin
[19:47:49] [I] SelectedLanguage: Russian
[19:47:49] [I] LocalizeIndex: Mandarin
[19:47:49] [I] SelectedLanguage: Russian
[19:47:49] [I] LocalizeIndex: Mandarin
[19:47:49] [I] SelectedLanguage: Russian
[19:47:49] [I] LocalizeIndex: Mandarin
[19:47:49] [I] SelectedLanguage: Russian
[19:47:49] [I] LocalizeIndex: Mandarin
[19:47:49] [I] SelectedLanguage: Russian
[19:47:49] [I] LocalizeIndex: Mandarin
[19:47:49] [I] SelectedLanguage: Russian
[19:47:49] [I] LocalizeIndex: Mandarin
[19:47:49] [I] SelectedLanguage: Russian
[19:47:49] [I] LocalizeIndex: Sounds
[19:47:49] [I] SelectedLanguage: Russian
[19:47:49] [I] Loaded Sounds (patch 0) audio bank: I:\Games\Titanfall2\r2\sound\general_stream.mstr
[19:47:49] [I] LocalizeIndex: Sounds
[19:47:49] [I] SelectedLanguage: Russian
[19:47:49] [I] Loaded Sounds (patch 1) audio bank: I:\Games\Titanfall2\r2\sound\general_stream_patch_1.mstr
[19:47:49] [I] LocalizeIndex: Sounds
[19:47:49] [I] SelectedLanguage: Russian
[19:47:49] [I] Loaded Sounds (patch 2) audio bank: I:\Games\Titanfall2\r2\sound\general_stream_patch_2.mstr
[19:47:49] [I] LocalizeIndex: Sounds
[19:47:49] [I] SelectedLanguage: Russian
[19:47:49] [I] Loaded Sounds (patch 3) audio bank: I:\Games\Titanfall2\r2\sound\general_stream_patch_3.mstr
[19:47:49] [I] LocalizeIndex: Sounds
[19:47:49] [I] SelectedLanguage: Russian
[19:47:49] [I] Loaded Sounds (patch 4) audio bank: I:\Games\Titanfall2\r2\sound\general_stream_patch_4.mstr
[19:47:49] [I] LocalizeIndex: Sounds
[19:47:49] [I] SelectedLanguage: Russian
[19:47:49] [I] Loaded Sounds (patch 5) audio bank: I:\Games\Titanfall2\r2\sound\general_stream_patch_5.mstr
[19:47:49] [I] LocalizeIndex: Sounds
[19:47:49] [I] SelectedLanguage: Russian
[19:47:49] [I] Loaded Sounds (patch 6) audio bank: I:\Games\Titanfall2\r2\sound\general_stream_patch_6.mstr
[19:47:49] [I] LocalizeIndex: Sounds
[19:47:49] [I] SelectedLanguage: Russian
[19:47:49] [I] Loaded Sounds (patch 7) audio bank: I:\Games\Titanfall2\r2\sound\general_stream_patch_7.mstr
[19:47:49] [I] LocalizeIndex: Sounds
[19:47:49] [I] SelectedLanguage: Russian
[19:47:49] [I] Loaded Sounds (patch 8) audio bank: I:\Games\Titanfall2\r2\sound\general_stream_patch_8.mstr
[19:50:32] [I] Load rpak: I:\Games\Titanfall2\r2\sound\general.mbnk
[19:50:32] [I] LocalizeIndex: Polish
[19:50:32] [I] SelectedLanguage: English
[19:50:32] [I] LocalizeIndex: Polish
[19:50:32] [I] SelectedLanguage: English
[19:50:32] [I] LocalizeIndex: Polish
[19:50:32] [I] SelectedLanguage: English
[19:50:32] [I] LocalizeIndex: Polish
[19:50:32] [I] SelectedLanguage: English
[19:50:32] [I] LocalizeIndex: Polish
[19:50:32] [I] SelectedLanguage: English
[19:50:32] [I] LocalizeIndex: Polish
[19:50:32] [I] SelectedLanguage: English
[19:50:32] [I] LocalizeIndex: Polish
[19:50:32] [I] SelectedLanguage: English
[19:50:32] [I] LocalizeIndex: Polish
[19:50:32] [I] SelectedLanguage: English
[19:50:32] [I] LocalizeIndex: Polish
[19:50:32] [I] SelectedLanguage: English
[19:50:32] [I] LocalizeIndex: Mandarin
[19:50:32] [I] SelectedLanguage: English
[19:50:32] [I] LocalizeIndex: Mandarin
[19:50:32] [I] SelectedLanguage: English
[19:50:32] [I] LocalizeIndex: Mandarin
[19:50:32] [I] SelectedLanguage: English
[19:50:32] [I] LocalizeIndex: Mandarin
[19:50:32] [I] SelectedLanguage: English
[19:50:32] [I] LocalizeIndex: Mandarin
[19:50:32] [I] SelectedLanguage: English
[19:50:32] [I] LocalizeIndex: Mandarin
[19:50:32] [I] SelectedLanguage: English
[19:50:32] [I] LocalizeIndex: Mandarin
[19:50:32] [I] SelectedLanguage: English
[19:50:32] [I] LocalizeIndex: Mandarin
[19:50:32] [I] SelectedLanguage: English
[19:50:32] [I] LocalizeIndex: Mandarin
[19:50:32] [I] SelectedLanguage: English
[19:50:32] [I] LocalizeIndex: Sounds
[19:50:32] [I] SelectedLanguage: English
[19:50:32] [I] Loaded Sounds (patch 0) audio bank: I:\Games\Titanfall2\r2\sound\general_stream.mstr
[19:50:32] [I] LocalizeIndex: Sounds
[19:50:32] [I] SelectedLanguage: English
[19:50:32] [I] Loaded Sounds (patch 1) audio bank: I:\Games\Titanfall2\r2\sound\general_stream_patch_1.mstr
[19:50:32] [I] LocalizeIndex: Sounds
[19:50:32] [I] SelectedLanguage: English
[19:50:32] [I] Loaded Sounds (patch 2) audio bank: I:\Games\Titanfall2\r2\sound\general_stream_patch_2.mstr
[19:50:32] [I] LocalizeIndex: Sounds
[19:50:32] [I] SelectedLanguage: English
[19:50:32] [I] Loaded Sounds (patch 3) audio bank: I:\Games\Titanfall2\r2\sound\general_stream_patch_3.mstr
[19:50:32] [I] LocalizeIndex: Sounds
[19:50:32] [I] SelectedLanguage: English
[19:50:32] [I] Loaded Sounds (patch 4) audio bank: I:\Games\Titanfall2\r2\sound\general_stream_patch_4.mstr
[19:50:32] [I] LocalizeIndex: Sounds
[19:50:32] [I] SelectedLanguage: English
[19:50:32] [I] Loaded Sounds (patch 5) audio bank: I:\Games\Titanfall2\r2\sound\general_stream_patch_5.mstr
[19:50:32] [I] LocalizeIndex: Sounds
[19:50:32] [I] SelectedLanguage: English
[19:50:32] [I] Loaded Sounds (patch 6) audio bank: I:\Games\Titanfall2\r2\sound\general_stream_patch_6.mstr
[19:50:32] [I] LocalizeIndex: Sounds
[19:50:32] [I] SelectedLanguage: English
[19:50:32] [I] Loaded Sounds (patch 7) audio bank: I:\Games\Titanfall2\r2\sound\general_stream_patch_7.mstr
[19:50:32] [I] LocalizeIndex: Sounds
[19:50:32] [I] SelectedLanguage: English
[19:50:32] [I] Loaded Sounds (patch 8) audio bank: I:\Games\Titanfall2\r2\sound\general_stream_patch_8.mstr
[19:50:49] [I] Load rpak: I:\Games\Titanfall2\r2\sound\general.mbnk
[19:50:50] [I] LocalizeIndex: Polish
[19:50:50] [I] SelectedLanguage: Polish
[19:50:50] [I] Loaded Polish (patch 0) audio bank: I:\Games\Titanfall2\r2\sound\general_polish.mstr
[19:50:50] [I] LocalizeIndex: Polish
[19:50:50] [I] SelectedLanguage: Polish
[19:50:50] [I] Loaded Polish (patch 1) audio bank: I:\Games\Titanfall2\r2\sound\general_polish_patch_1.mstr
[19:50:50] [I] LocalizeIndex: Polish
[19:50:50] [I] SelectedLanguage: Polish
[19:50:50] [I] Loaded Polish (patch 2) audio bank: I:\Games\Titanfall2\r2\sound\general_polish_patch_2.mstr
[19:50:50] [I] LocalizeIndex: Polish
[19:50:50] [I] SelectedLanguage: Polish
[19:50:50] [I] Loaded Polish (patch 3) audio bank: I:\Games\Titanfall2\r2\sound\general_polish_patch_3.mstr
[19:50:50] [I] LocalizeIndex: Polish
[19:50:50] [I] SelectedLanguage: Polish
[19:50:50] [I] Loaded Polish (patch 4) audio bank: I:\Games\Titanfall2\r2\sound\general_polish_patch_4.mstr
[19:50:50] [I] LocalizeIndex: Polish
[19:50:50] [I] SelectedLanguage: Polish
[19:50:50] [I] Loaded Polish (patch 5) audio bank: I:\Games\Titanfall2\r2\sound\general_polish_patch_5.mstr
[19:50:50] [I] LocalizeIndex: Polish
[19:50:50] [I] SelectedLanguage: Polish
[19:50:50] [I] Loaded Polish (patch 6) audio bank: I:\Games\Titanfall2\r2\sound\general_polish_patch_6.mstr
[19:50:50] [I] LocalizeIndex: Polish
[19:50:50] [I] SelectedLanguage: Polish
[19:50:50] [I] Loaded Polish (patch 7) audio bank: I:\Games\Titanfall2\r2\sound\general_polish_patch_7.mstr
[19:50:50] [I] LocalizeIndex: Polish
[19:50:50] [I] SelectedLanguage: Polish
[19:50:50] [I] Loaded Polish (patch 8) audio bank: I:\Games\Titanfall2\r2\sound\general_polish_patch_8.mstr
[19:50:50] [I] LocalizeIndex: Mandarin
[19:50:50] [I] SelectedLanguage: Polish
[19:50:50] [I] LocalizeIndex: Mandarin
[19:50:50] [I] SelectedLanguage: Polish
[19:50:50] [I] LocalizeIndex: Mandarin
[19:50:50] [I] SelectedLanguage: Polish
[19:50:50] [I] LocalizeIndex: Mandarin
[19:50:50] [I] SelectedLanguage: Polish
[19:50:50] [I] LocalizeIndex: Mandarin
[19:50:50] [I] SelectedLanguage: Polish
[19:50:50] [I] LocalizeIndex: Mandarin
[19:50:50] [I] SelectedLanguage: Polish
[19:50:50] [I] LocalizeIndex: Mandarin
[19:50:50] [I] SelectedLanguage: Polish
[19:50:50] [I] LocalizeIndex: Mandarin
[19:50:50] [I] SelectedLanguage: Polish
[19:50:50] [I] LocalizeIndex: Mandarin
[19:50:50] [I] SelectedLanguage: Polish
[19:50:50] [I] LocalizeIndex: Sounds
[19:50:50] [I] SelectedLanguage: Polish
[19:50:50] [I] Loaded Sounds (patch 0) audio bank: I:\Games\Titanfall2\r2\sound\general_stream.mstr
[19:50:50] [I] LocalizeIndex: Sounds
[19:50:50] [I] SelectedLanguage: Polish
[19:50:50] [I] Loaded Sounds (patch 1) audio bank: I:\Games\Titanfall2\r2\sound\general_stream_patch_1.mstr
[19:50:50] [I] LocalizeIndex: Sounds
[19:50:50] [I] SelectedLanguage: Polish
[19:50:50] [I] Loaded Sounds (patch 2) audio bank: I:\Games\Titanfall2\r2\sound\general_stream_patch_2.mstr
[19:50:50] [I] LocalizeIndex: Sounds
[19:50:50] [I] SelectedLanguage: Polish
[19:50:50] [I] Loaded Sounds (patch 3) audio bank: I:\Games\Titanfall2\r2\sound\general_stream_patch_3.mstr
[19:50:50] [I] LocalizeIndex: Sounds
[19:50:50] [I] SelectedLanguage: Polish
[19:50:50] [I] Loaded Sounds (patch 4) audio bank: I:\Games\Titanfall2\r2\sound\general_stream_patch_4.mstr
[19:50:50] [I] LocalizeIndex: Sounds
[19:50:50] [I] SelectedLanguage: Polish
[19:50:50] [I] Loaded Sounds (patch 5) audio bank: I:\Games\Titanfall2\r2\sound\general_stream_patch_5.mstr
[19:50:50] [I] LocalizeIndex: Sounds
[19:50:50] [I] SelectedLanguage: Polish
[19:50:50] [I] Loaded Sounds (patch 6) audio bank: I:\Games\Titanfall2\r2\sound\general_stream_patch_6.mstr
[19:50:50] [I] LocalizeIndex: Sounds
[19:50:50] [I] SelectedLanguage: Polish
[19:50:50] [I] Loaded Sounds (patch 7) audio bank: I:\Games\Titanfall2\r2\sound\general_stream_patch_7.mstr
[19:50:50] [I] LocalizeIndex: Sounds
[19:50:50] [I] SelectedLanguage: Polish
[19:50:50] [I] Loaded Sounds (patch 8) audio bank: I:\Games\Titanfall2\r2\sound\general_stream_patch_8.mstr
[19:50:59] [I] Load rpak: I:\Games\Titanfall2\r2\sound\general.mbnk
[19:50:59] [I] LocalizeIndex: Polish
[19:50:59] [I] SelectedLanguage: Mandarin
[19:50:59] [I] LocalizeIndex: Polish
[19:50:59] [I] SelectedLanguage: Mandarin
[19:50:59] [I] LocalizeIndex: Polish
[19:50:59] [I] SelectedLanguage: Mandarin
[19:50:59] [I] LocalizeIndex: Polish
[19:50:59] [I] SelectedLanguage: Mandarin
[19:50:59] [I] LocalizeIndex: Polish
[19:50:59] [I] SelectedLanguage: Mandarin
[19:50:59] [I] LocalizeIndex: Polish
[19:50:59] [I] SelectedLanguage: Mandarin
[19:50:59] [I] LocalizeIndex: Polish
[19:50:59] [I] SelectedLanguage: Mandarin
[19:50:59] [I] LocalizeIndex: Polish
[19:50:59] [I] SelectedLanguage: Mandarin
[19:50:59] [I] LocalizeIndex: Polish
[19:50:59] [I] SelectedLanguage: Mandarin
[19:50:59] [I] LocalizeIndex: Mandarin
[19:50:59] [I] SelectedLanguage: Mandarin
[19:50:59] [I] Loaded Mandarin (patch 0) audio bank: I:\Games\Titanfall2\r2\sound\general_russian.mstr
[19:50:59] [I] LocalizeIndex: Mandarin
[19:50:59] [I] SelectedLanguage: Mandarin
[19:50:59] [I] Loaded Mandarin (patch 1) audio bank: I:\Games\Titanfall2\r2\sound\general_russian_patch_1.mstr
[19:50:59] [I] LocalizeIndex: Mandarin
[19:50:59] [I] SelectedLanguage: Mandarin
[19:50:59] [I] Loaded Mandarin (patch 2) audio bank: I:\Games\Titanfall2\r2\sound\general_russian_patch_2.mstr
[19:50:59] [I] LocalizeIndex: Mandarin
[19:50:59] [I] SelectedLanguage: Mandarin
[19:50:59] [I] Loaded Mandarin (patch 3) audio bank: I:\Games\Titanfall2\r2\sound\general_russian_patch_3.mstr
[19:50:59] [I] LocalizeIndex: Mandarin
[19:50:59] [I] SelectedLanguage: Mandarin
[19:50:59] [I] Loaded Mandarin (patch 4) audio bank: I:\Games\Titanfall2\r2\sound\general_russian_patch_4.mstr
[19:50:59] [I] LocalizeIndex: Mandarin
[19:50:59] [I] SelectedLanguage: Mandarin
[19:50:59] [I] Loaded Mandarin (patch 5) audio bank: I:\Games\Titanfall2\r2\sound\general_russian_patch_5.mstr
[19:50:59] [I] LocalizeIndex: Mandarin
[19:50:59] [I] SelectedLanguage: Mandarin
[19:50:59] [I] Loaded Mandarin (patch 6) audio bank: I:\Games\Titanfall2\r2\sound\general_russian_patch_6.mstr
[19:50:59] [I] LocalizeIndex: Mandarin
[19:50:59] [I] SelectedLanguage: Mandarin
[19:50:59] [I] Loaded Mandarin (patch 7) audio bank: I:\Games\Titanfall2\r2\sound\general_russian_patch_7.mstr
[19:50:59] [I] LocalizeIndex: Mandarin
[19:50:59] [I] SelectedLanguage: Mandarin
[19:50:59] [I] Loaded Mandarin (patch 8) audio bank: I:\Games\Titanfall2\r2\sound\general_russian_patch_8.mstr
[19:50:59] [I] LocalizeIndex: Sounds
[19:50:59] [I] SelectedLanguage: Mandarin
[19:50:59] [I] Loaded Sounds (patch 0) audio bank: I:\Games\Titanfall2\r2\sound\general_stream.mstr
[19:50:59] [I] LocalizeIndex: Sounds
[19:50:59] [I] SelectedLanguage: Mandarin
[19:50:59] [I] Loaded Sounds (patch 1) audio bank: I:\Games\Titanfall2\r2\sound\general_stream_patch_1.mstr
[19:50:59] [I] LocalizeIndex: Sounds
[19:50:59] [I] SelectedLanguage: Mandarin
[19:50:59] [I] Loaded Sounds (patch 2) audio bank: I:\Games\Titanfall2\r2\sound\general_stream_patch_2.mstr
[19:50:59] [I] LocalizeIndex: Sounds
[19:50:59] [I] SelectedLanguage: Mandarin
[19:50:59] [I] Loaded Sounds (patch 3) audio bank: I:\Games\Titanfall2\r2\sound\general_stream_patch_3.mstr
[19:50:59] [I] LocalizeIndex: Sounds
[19:50:59] [I] SelectedLanguage: Mandarin
[19:50:59] [I] Loaded Sounds (patch 4) audio bank: I:\Games\Titanfall2\r2\sound\general_stream_patch_4.mstr
[19:50:59] [I] LocalizeIndex: Sounds
[19:50:59] [I] SelectedLanguage: Mandarin
[19:50:59] [I] Loaded Sounds (patch 5) audio bank: I:\Games\Titanfall2\r2\sound\general_stream_patch_5.mstr
[19:50:59] [I] LocalizeIndex: Sounds
[19:50:59] [I] SelectedLanguage: Mandarin
[19:50:59] [I] Loaded Sounds (patch 6) audio bank: I:\Games\Titanfall2\r2\sound\general_stream_patch_6.mstr
[19:50:59] [I] LocalizeIndex: Sounds
[19:50:59] [I] SelectedLanguage: Mandarin
[19:50:59] [I] Loaded Sounds (patch 7) audio bank: I:\Games\Titanfall2\r2\sound\general_stream_patch_7.mstr
[19:50:59] [I] LocalizeIndex: Sounds
[19:50:59] [I] SelectedLanguage: Mandarin
[19:50:59] [I] Loaded Sounds (patch 8) audio bank: I:\Games\Titanfall2\r2\sound\general_stream_patch_8.mstr
```

**Comment by biast12** [comment]
MilesLanguageIDs is not made or designed in Titanfall 2 in mind, mainly only Apex, we may look into adding it at some point but it's likely not gonna be now or any time soon

**Comment by begin-theadventure** [comment]
I just tried Russian with diag viper sounds, and unfortunately Legion+ can't export them.

**Comment by biast12** [comment]
as said before Legion+ does not support languages for Titanfall 2, it only works for english, and it's properly never gonna work with other languages

**Comment by biast12** [comment]
@IJARika maybe it would be an idea to close this unless you wanna work on adding it

**Comment by IJARika** [comment]
Issue has not been resolved, so it will stay open. I don't really understand miles that well, but maybe I can take a look. 

Alternatively if you know the fix feel free to make a pull request.

**Comment by begin-theadventure** [comment]
Can Miles-10-Sound-Dumper export languages that Legion+ can't?

**Comment by biast12** [comment]
> Issue has not been resolved, so it will stay open. I don't really understand miles that well, but maybe I can take a look.

fair, i was more thinking it's not really a bug just more like a feature that's not build to work on Titanfall 2 too

> Could you verify if this is also an issue for Apex?

it works for Apex, it's just an issue for Titanfall 2 since the MilesLanguageIDs is ordered in another way than apex

> Alternatively if you know the fix feel free to make a pull request.

i'm not sure how i could be able to split it into using one order of MilesLanguageIDs for apex VS having another order for Titanfall 2, that's kinda the issue here, it only got the order for Apex

**Comment by biast12** [comment]
> Can Miles-10-Sound-Dumper export languages that Legion+ can't?

you should be able to use Miles, but idk if the current version got languages support, Shrug gave me a version that supported it but i don't remember what the flags were, you can download it [here](https://biast12.site/?r=/download&path=L0FwZXhfUENfQXJjaGl2ZS8hVG9vbHMgZm9yIEdldHRpbmcgdGhlIGZpbGVzL01pbGVzIFNvdW5kIER1bXBlci9NU0QuZXhl)

**Comment by IJARika** [comment]
So when you try to export those languages in Apex (spanish portuguese etc) it works fine?

**Comment by biast12** [comment]
> So when you try to export those languages in Apex (spanish portuguese etc) it works fine?

yep, this is only a Titanfall 2 issue really, because the whole languages system is not set up for Titanfall 2, it's only MilesLanguageID order of Apex

it's not really a bug, it's more just not made to support Titanfall 2 too

**Comment by IJARika** [comment]
#123 @Gazyi @begin-theadventure @biast12 feel free to build this and give a test, should fix russian language exporting.

**Comment by IJARika** [comment]
fixed in #123

**Comment by begin-theadventure** [comment]
Thanks.
I downloaded the nightly version and tried now with the same language and diags, but unfortunately I still get the error.

**Comment by begin-theadventure** [comment]
Thanks.
I downloaded the nightly version and tried it with the same language and diags, I still got the error, but that's because I didn't change the `Audio Language` in `Settings` 😅.
Thank you very much for fixing this!! Now it works.
